---
# Defines tasks for Debian installation

- name: Check if already installed
  stat: >
    path="{{ nginx_config_dir }}/nginx.conf"
  register: nginx_installed
  tags:
    - nginx

- name: Update packages cache if not installed
  apt: >
    update_cache=yes
    cache_valid_time=86400
  when: nginx_installed.stat.exists == false
  tags:
    - nginx

- name: Remove Apache packages
  apt: >
    pkg="{{ item }}"
    state=absent
    purge=yes
  with_items: "{{apache_packages}}"
  when: nginx_remove_apache
  tags:
    - nginx

- name: Install packages
  apt: >
    name="{{ item }}"
    state=latest
  with_items: "{{ nginx_packages }}"
  tags:
    - nginx
